name: UI Tests

on:
  push:
    branches: [ "main" ]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    env:
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Selenium Docker image
        run: |
          docker build -t selenium-tests ./selenium-ui-automation

      - name: Run tests inside Docker
        run: |
          mkdir -p selenium-ui-automation/allure-results
          docker run --rm \
            -e USER_PASSWORD="${{ secrets.USER_PASSWORD }}" \
            -v "${{ github.workspace }}/selenium-ui-automation/allure-results:/app/allure-results" \
            selenium-tests

      - name: Upload Allure results from Docker run
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-docker
          path: selenium-ui-automation/allure-results
